
import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  es: {
    // General
    loading: "Cargando...",
    cancel: "Cancelar",
    save: "Guardar",
    edit: "Editar",
    delete: "Eliminar",
    view: "Ver",
    actions: "Acciones",
    search: "Buscar...",
    seeAll: "Ver todos",
    noDescription: "Sin descripción",
    confirmDelete: "¿Seguro que deseas eliminar {count} riesgo(s)?",
    errorDeleting: "Error al eliminar los riesgos.",
    deleting: "Eliminando...",
    
    // Niveles de Riesgo
    intolerable: "Intolerable",
    high: "Alto",
    medium: "Medio",
    low: "Bajo",
    tolerable: "Tolerable",
    unclassified: "Sin clasificar",

    // Layout & Login
    riskManagement: "Matriz de Riesgos",
    professionalManagement: "Gestión Profesional",
    dashboard: "Dashboard",
    departments: "Departamentos",
    allRisks: "Matriz de Riesgos",
    addRisk: "Agregar Riesgo",
    lightMode: "Modo Claro",
    darkMode: "Modo Oscuro",
    logout: "Cerrar Sesión",
    
    // New Login Translations
    loginWelcomeTitle: "Bienvenido de Vuelta",
    loginWelcomeSubtitle: "Ingresa a tu sistema de gestión de riesgos",
    loginHeroSubtitle: "Sistema profesional para la identificación, evaluación y gestión integral de riesgos organizacionales",
    loginButton: "Iniciar Sesión",
    loginButtonLoading: "Iniciando Sesión...",
    loginDisclaimer: "Al iniciar sesión, aceptas que tus datos se mantendrán privados y seguros",
    
    // Login Features
    loginFeature1Title: "Acceso Seguro",
    loginFeature1Description: "Autenticación con tu cuenta Google de forma segura y rápida",
    loginFeature2Title: "Datos Privados",
    loginFeature2Description: "Tu información está protegida con cifrado de nivel empresarial",
    loginFeature3Title: "Matriz Profesional",
    loginFeature3Description: "Herramientas avanzadas para la gestión completa de riesgos",
    loginNoAccount: "¿No tienes cuenta?",
    loginRegisterLink: "Regístrate aquí",
    forgotPassword: "¿Olvidaste tu contraseña?",
    loginError: "Error al iniciar sesión",
    invalidCredentials: "Email o contraseña incorrectos",
    accountSuspended: "Tu cuenta ha sido suspendida. Contacta al administrador.",


    // Forgot Password & Update Password
    recoverPasswordTitle: "Recuperar Contraseña",
    recoverPasswordSubtitle: "Ingresa tu email para recibir un enlace de recuperación.",
    emailRequired: "El email es obligatorio",
    recoverPasswordSuccess: "Revisa tu email para el enlace de recuperación",
    recoverPasswordError: "Error al enviar el email. Intenta nuevamente.",
    sending: "Enviando...",
    emailSent: "Email Enviado",
    sendRecoveryLink: "Enviar Enlace",
    backToLogin: "Volver al Login",
    
    updatePasswordTitle: "Nueva Contraseña",
    updatePasswordSubtitle: "Ingresa tu nueva contraseña continuación.",
    passwordUpdatedSuccess: "Contraseña actualizada exitosamente",
    updatePasswordError: "Error al actualizar contraseña. Intenta nuevamente.",
    updating: "Actualizando...",
    updated: "Actualizada",
    updatePassword: "Actualizar Contraseña",


    // Register Page
    registerTitle: "Crear Nueva Cuenta",
    registerSubtitle: "Regístrate con tu código de invitación",
    registerHeroSubtitle: "Únete a nuestra plataforma profesional de gestión de riesgos",
    registerFullName: "Nombre Completo",
    registerConfirmPassword: "Confirmar Contraseña",
    registerInvitationCode: "Código de Invitación",
    registerButton: "Crear Cuenta",
    registerButtonLoading: "Creando Cuenta...",
    registerSuccess: "¡Cuenta creada exitosamente! Redirigiendo...",
    registerAlreadyHaveAccount: "¿Ya tienes cuenta?",
    registerLoginLink: "Inicia sesión",
    registerCodeInfo: "Necesitas un código de invitación válido para registrarte",

    // Register Form Validation
    registerAllFieldsRequired: "Todos los campos son obligatorios",
    registerPasswordTooShort: "La contraseña debe tener al menos 6 caracteres",
    registerPasswordsDoNotMatch: "Las contraseñas no coinciden",
    registerInvalidEmail: "El correo electrónico no es válido",
    registerInvalidCode: "El código de invitación no es válido",
    registerCodeUsed: "Este código ya ha sido utilizado",
    registerCodeExpired: "El código de invitación ha expirado",
    registerEmailExists: "Este correo electrónico ya está registrado",
    registerError: "Error al crear la cuenta. Intenta nuevamente.",

    // Register Features
    registerFeature1Title: "Acceso Exclusivo",
    registerFeature1Description: "Registro solo por invitación para mantener la calidad del servicio",
    registerFeature2Title: "Datos Seguros",
    registerFeature2Description: "Tu información protegida con los más altos estándares de seguridad",
    registerFeature3Title: "Herramientas Pro",
    registerFeature3Description: "Acceso completo a todas las funcionalidades profesionales",

    // Dashboard
    welcome: "¡Bienvenido!",
    dashboardHeaderSubtitle: "Gestiona los riesgos de tu organización de manera profesional",
    newRisk: "Nuevo Riesgo",
    active: "Activos",
    totalRisks: "Riesgos Totales",
    identified: "Identificados",
    highRisks: "Riesgos Altos",
    immediateAttention: "Atención inmediata",
    lowRisks: "Riesgos Bajos",
    underControl: "Bajo control",
    recentDepartments: "Departamentos Recientes",
    noDepartmentsRegistered: "No hay departamentos registrados",
    createFirstDepartment: "Crear primer departamento",
    riskDistribution: "Distribución de Riesgos",
    noRisksRegistered: "No hay riesgos registrados",
    registerFirstRisk: "Registrar primer riesgo",

    // Departments Page
    departmentsTitle: "Departamentos",
    departmentsSubtitle: "Gestiona los departamentos y sus riesgos asociados",
    newDepartment: "Nuevo Departamento",
    totalRisksLabel: "Riesgos Totales",
    highRisksLabel: "Riesgos Altos",
    viewRisks: "Ver Riesgos",
    noDepartmentsFound: "No hay departamentos",
    noDepartmentsFoundSubtitle: "Comienza creando tu primer departamento para gestionar los riesgos",
    
    // AddDepartment Page
    addDepartmentTitle: "Nuevo Departamento",
    addDepartmentSubtitle: "Crea un nuevo departamento para gestionar riesgos",
    editDepartmentTitle: "Editar Departamento",
    editDepartmentSubtitle: "Actualiza los detalles del departamento",
    departmentInfo: "Información del Departamento",
    departmentNameLabel: "Nombre del Departamento *",
    departmentNamePlaceholder: "Ej: Recursos Humanos, IT, Finanzas...",
    descriptionLabel: "Descripción (Opcional)",
    descriptionPlaceholder: "Describe las funciones principales del departamento...",
    creating: "Creando...",
    createDepartment: "Crear Departamento",
    errorRequiredName: "El nombre del departamento es obligatorio",
    errorCreatingDepartment: "Error al crear el departamento. Intenta nuevamente.",
    errorUpdatingDepartment: "Error al actualizar el departamento. Intenta nuevamente.",
    departmentNotFound: "Departamento no encontrado.",

    // Risk Pages (General)
    riskInfo: "Información Básica",
    departmentLabel: "Departamento *",
    departmentPlaceholder: "Selecciona departamento",
    threatTypeLabel: "Tipo de Amenaza *",
    threatTypePlaceholder: "Selecciona tipo",
    threatInternal: "Interna",
    threatExternal: "Externa",
    riskDescriptionLabel: "Descripción del Riesgo *",
    riskDescriptionPlaceholder: "Describe detalladamente el riesgo...",
    inherentRiskEval: "Evaluación de Riesgo Inherente",
    inherentProbability: "Probabilidad Inherente",
    inherentImpact: "Impacto Inherente",
    selectProbability: "Selecciona probabilidad",
    selectImpact: "Selecciona impacto",
    inherentRiskLevel: "Nivel de Riesgo Inherente:",
    strategyAndMitigation: "Estrategia y Mitigación",
    managementStrategy: "Estrategia de Manejo",
    selectStrategy: "Selecciona estrategia",
    strategyAceptar: "Aceptar",
    strategyReducir: "Reducir",
    strategyTransferir: "Transferir",
    strategyEvitar: "Evitar",
    mitigationMeasure: "Medida de Mitigación {num}",
    mitigationDescription: "Describe la medida {num}...",
    mitigationImpact: "Impacto esperado...",
    selectMitigationImpact: "Selecciona el tipo de mitigación...",
    "Mitiga la probabilidad": "Mitiga la probabilidad",
    "Mitiga el impacto": "Mitiga el impacto",
    "Mitiga la probabilidad e impacto": "Mitiga la probabilidad e impacto",
    residualRisk: "Riesgo Residual",
    residualProbability: "Probabilidad Residual",
    residualImpact: "Impacto Residual",
    residualRiskLevel: "Nivel de Riesgo Residual:",
    saving: "Guardando...",
    saveChanges: "Guardar Cambios",
    registerRisk: "Registrar Riesgo",
    errorRequiredFields: "Por favor completa todos los campos obligatorios (*)",
    errorSavingRisk: "Error al guardar el riesgo. Intenta nuevamente.",
    riskNotFound: "Riesgo no encontrado.",
    dataLoadError: "No se pudieron cargar los datos necesarios.",

    // AddRisk Page
    addRiskTitle: "Registrar Nuevo Riesgo",
    addRiskSubtitle: "Documenta y evalúa un riesgo organizacional",
    editRiskTitle: "Editar Riesgo",
    editRiskSubtitle: "Actualiza los detalles del riesgo",

    // DepartmentRisks Page
    departmentRiskManagement: "Gestión de riesgos del departamento",
    filtersAndSearch: "Filtros y Búsqueda",
    searchRisksPlaceholder: "Buscar riesgos...",
    riskLevelLabel: "Nivel de riesgo",
    allLevels: "Todos los niveles",
    allThreats: "Todas las amenazas",
    riskList: "Lista de Riesgos ({count})",
    tableDescription: "Descripción",
    tableType: "Tipo",
    tableInherentLevel: "Nivel Inherente",
    tableResidualLevel: "Nivel Residual",
    tableStrategy: "Estrategia",
    noRisksFound: "No se encontraron riesgos",
    noRisksInDepartment: "No hay riesgos registrados en este departamento",
    noRisksMatchFilters: "No hay riesgos que coincidan con los filtros",
    
    // AllRisks Page
    allRisksTitle: "Matriz de Riesgos",
    allRisksSubtitle: "Vista centralizada de todos los riesgos de la organización",
    deleteSelected: "Eliminar ({count})",
    searchAllPlaceholder: "Buscar por área, descripción...",
    allDepartments: "Todos los departamentos",
    showingRisks: "Mostrando {count} de {total} riesgos",
    tableDepartment: "Departamento",
    tableThreatType: "Tipo Amenaza",
    tableInherentProb: "Probabilidad",
    tableInherentImp: "Impacto",
    tableInherentLvl: "Nivel",
    tableHandling: "Manejo",
    tableMitigant1: "Mitigante 1",
    tableMitigant2: "Mitigante 2", 
    tableMitigant3: "Mitigante 3",
    tableImpact: "Impacto",
    tableImpact1: "Impacto 1",
    tableImpact2: "Impacto 2", 
    tableImpact3: "Impacto 3",
    tableResidualProb: "Probabilidad",
    tableResidualImp: "Impacto",
    tableResidualLvl: "Nivel",
    
    // Probabilidades e Impactos (enums)
    "Remoto (0-20%)": "Remoto (0-20%)",
    "Improbable (21-40%)": "Improbable (21-40%)",
    "Ocasional (41-60%)": "Ocasional (41-60%)",
    "Probable (61-80%)": "Probable (61-80%)",
    "Frecuente (81-100%)": "Frecuente (81-100%)",
    "Insignificante": "Insignificante",
    "Menor": "Menor",
    "Crítico": "Crítico",
    "Mayor": "Mayor",
    "Catastrófico": "Catastrófico",

    // Control Evaluation (Tipo y Grado de Control)
    controlEvaluation: "Evaluación del Control",
    controlType: "Tipo de Control",
    controlPreventive: "Control Preventivo",
    controlCorrective: "Control Correctivo",
    controlDetective: "Control Detectivo",
    controlDocumented: "¿Control documentado?",
    processType: "Tipo de procesos",
    processManual: "Manual",
    processAutomated: "Automatizado",
    processCombined: "Combinado",
    controlEvidence: "¿Genera evidencia auditable?",
    controlResponsible: "¿Tiene responsable?",
    controlFrequency: "¿Se ejecuta con frecuencia?",
    controlGrade: "Grado de Control",
    gradeStrong: "Fuerte",
    gradeMedium: "Medio",
    gradeWeak: "Débil",
    yes: "Sí",
    no: "No",
    selectControlType: "Selecciona tipo de control...",
    selectProcessType: "Selecciona tipo de proceso...",
    selectYesNo: "Selecciona...",
    tableControlType1: "Tipo Control 1",
    tableControlGrade1: "Grado Control 1",
    tableControlType2: "Tipo Control 2",
    tableControlGrade2: "Grado Control 2",
    tableControlType3: "Tipo Control 3",
    tableControlGrade3: "Grado Control 3",

    // Access Control
    accessDenied: "Acceso Denegado",
    adminOnlyFeature: "Esta función está disponible solo para administradores.",
    contactAdminAccess: "Si necesitas acceso, contacta al administrador del sistema.",

    // Invitation Codes Page
    invitationCodes: "Códigos de Invitación",
    codesTitle: "Códigos de Invitación",
    codesSubtitle: "Gestiona los códigos de acceso para nuevos usuarios",
    codesCreateButton: "Generar Código",
    codesCreateTitle: "Generar Nuevo Código",
    codesCreateDescription: "Crea un código de invitación para permitir el registro de un nuevo usuario",
    codesEmailLabel: "Email del Usuario",
    codesEmailPlaceholder: "usuario@ejemplo.com",
    codesEmailHelp: "Opcional: vincula este código a un email específico",
    codesNotesLabel: "Notas",
    codesNotesPlaceholder: "Cliente pagó plan mensual, etc.",
    codesExpiryLabel: "Fecha de Expiración",
    optional: "opcional",
    create: "Crear",
    creating: "Creando...",
    codesStatTotal: "Total de Códigos",
    codesStatUsed: "Códigos Usados",
    codesStatAvailable: "Códigos Disponibles",
    codesListTitle: "Todos los Códigos",
    codesListDescription: "Gestiona y monitorea el uso de códigos de invitación",
    codesEmpty: "No hay códigos de invitación aún",
    codesTableCode: "Código",
    codesTableStatus: "Estado",
    codesTableEmail: "Email",
    codesTableNotes: "Notas",
    codesTableCreated: "Creado",
    codesTableExpires: "Expira",
    codesTableActions: "Acciones",
    codesStatusUsed: "Usado",
    codesStatusExpired: "Expirado",
    codesStatusAvailable: "Disponible",
    codesDeleteTitle: "¿Eliminar Código?",
    codesDeleteDescription: "Esta acción no se puede deshacer. El código será eliminado permanentemente.",
    codesLoadError: "Error al cargar códigos",
    codeCreatedSuccess: "Código creado exitosamente",
    codeCreateError: "Error al crear el código",
    codeDeletedSuccess: "Código eliminado exitosamente",
    codeDeleteError: "Error al eliminar el código",
    codeCopied: "Código copiado al portapapeles",
    codeCopyError: "Error al copiar el código",

    // User Management Page
    userManagement: "Gestión de Usuarios",
    usersTitle: "Gestión de Usuarios",
    usersSubtitle: "Administra las cuentas de usuario del sistema",
    usersRefresh: "Actualizar",
    usersStatTotal: "Total de Usuarios",
    usersStatActive: "Usuarios Activos",
    usersStatSuspended: "Usuarios Suspendidos",
    usersSearchPlaceholder: "Buscar por nombre o email...",
    usersListTitle: "Todos los Usuarios",
    usersShowingCount: "Mostrando {count} de {total} usuarios",
    usersEmpty: "No hay usuarios registrados",
    usersTableName: "Nombre",
    usersTableEmail: "Email",
    usersTableRole: "Rol",
    usersTableStatus: "Estado",
    usersTableCreated: "Registrado",
    usersTableLastLogin: "Último Acceso",
    usersStatusActive: "Activo",
    usersStatusSuspended: "Suspendido",
    usersYou: "(Tú)",
    usersSuspendBtn: "Suspender",
    usersReactivateBtn: "Reactivar",
    usersSuspendTitle: "¿Suspender usuario?",
    usersSuspendDescription: "El usuario no podrá iniciar sesión hasta que sea reactivado. Sus datos se conservarán.",
    usersReactivateTitle: "¿Reactivar usuario?",
    usersReactivateDescription: "El usuario podrá iniciar sesión nuevamente.",
    userSuspendedSuccess: "Usuario suspendido exitosamente",
    userSuspendError: "Error al suspender el usuario",
    userReactivatedSuccess: "Usuario reactivado exitosamente",
    userReactivateError: "Error al reactivar el usuario",
    usersLoadError: "Error al cargar los usuarios",

    // Finance System - Dashboard
    finDashboardTitle: "Sistema de Planeación",
    finDashboardSubtitle: "Planeación empresarial y financiera integral",
    finBizPlanningTitle: "Planeación Empresarial",
    finBizPlanningSubtitle: "Análisis de mercado, interno, cliente y situación financiera",
    finFinPlanningTitle: "Planeación Financiera",
    finFinPlanningSubtitle: "Datos históricos, proyecciones y análisis actual",
    finBizAnalysis: "Análisis Empresarial",
    finBizAnalysisDesc: "Mercado, análisis interno, cliente y estado de resultados",
    finSwot: "FODA y Conclusiones",
    finSwotDesc: "Matriz FODA, resumen de estrategias y cronograma",
    finHistorical: "Análisis Histórico",
    finHistoricalDesc: "Datos históricos de ventas, estado de resultados y flujo de efectivo",
    finProjection: "Proyección Financiera",
    finProjectionDesc: "Herramientas de proyección, consulta y cotizadores",
    finCurrent: "Análisis Actual",
    finCurrentDesc: "Captura de datos reales y comparativo vs presupuesto",
    finEnter: "Ingresar",
    finStatRevenue: "Ingresos Anuales",
    finStatMargin: "Margen Bruto",
    finStatStrategies: "Estrategias",
    finStatActive: "activas",
    finStatPeriod: "Período Actual",
    finStatInProgress: "En curso",
    finPlanning: "Planeación",

    // Finance - Business Analysis
    finBizAnalysisPageDesc: "Análisis comparativo del mercado, interno, del cliente y financiero",
    finTabMarket: "El Mercado",
    finTabInternal: "Análisis Interno",
    finTabCustomer: "El Cliente",
    finTabFinStatus: "Estado de Resultados",
    finSubTabCompetitors: "Tus Competidores",
    finSubTabPosition: "Tu Posición en el Mercado",
    finSubTabExternal: "Tu Entorno Externo",
    finCompetitorAnalysis: "Análisis Comparativo de Competidores",
    finCompetitor: "Competidor",
    finPrice: "Precio",
    finService: "Servicio",
    finPostSale: "Post-Venta",
    finDelivery: "Entrega",
    finMarketPosition: "Tu Posición en el Mercado",
    finStrengths: "Fortalezas",
    finWeaknessesToManage: "Debilidades a Gestionar",
    finExternalEnv: "Tu Entorno Externo",
    finOpportunities: "Oportunidades",
    finThreats: "Amenazas",
    finInternalAnalysis: "Análisis Interno del Negocio",
    finCustomerAnalysis: "Análisis del Cliente",
    finCustProblem: "¿Qué problema(s) resuelve tu producto/servicio?",
    finCustDesire: "¿Qué deseo(s) atiende?",
    finCustFunctionalGoals: "Metas funcionales del cliente",
    finCustEmotionalGoals: "Metas emocionales del cliente",
    finCustBasicNeeds: "Deseos básicos del cliente",
    finFinancialStatus: "Análisis de Situación Financiera",
    finCategory: "Categoría",
    finIsWeakness: "¿Es Debilidad?",
    finDescription: "Descripción",
    finGoToConclusions: "Ir a Conclusiones",

    // Finance - SWOT / Conclusions
    finConclusionsTitle: "Conclusiones",
    finConclusionsSubtitle: "FODA, resumen de estrategias y cronograma",
    finSwotMatrix: "Matriz FODA",
    finStrategySummary: "Resumen de Estrategias",
    finTimeline: "Cronograma",
    finWeaknesses: "Debilidades",
    finThreatsLabel: "Amenazas",
    finAddItem: "Agregar elemento",
    finTask: "Tarea",
    finResponsible: "Responsable",
    finStart: "Inicio",
    finEnd: "Fin",
    finStatus: "Estado",
    finStatusCompleted: "Completado",
    finStatusInProgress: "En Progreso",
    finStatusPending: "Pendiente",

    // Finance - Financial History
    finHistoricalPageDesc: "Captura y consulta de datos financieros históricos",
    finSalesData: "Datos de Ventas",
    finIncomeStatement: "Estado de Resultados",
    finCashFlow: "Flujo de Efectivo",
    finHistSales: "Ventas Históricas",
    finReturns: "Devoluciones",
    finNetTotals: "Ventas Netas",
    finPrint: "Imprimir",
    finProductLine: "Línea de Producto",
    finConcept: "Concepto",
    finAll: "Todos",
    finOperationActivities: "Actividades de Operación",
    finOperationFlow: "Flujo por Operación",
    finInvestActivities: "Actividades de Inversión",

    // Finance - Projection
    finProjectionPageDesc: "Herramientas de proyección financiera y cotizadores",
    finProjMenu: "Menú Proyección",
    finProjConsult: "Consulta Proyección",
    finQuotation: "Cotizadores",
    finProjVsBase: "Proyecciones mensuales vs año base",
    finPosition: "Puesto",
    finMonthlySalary: "Sueldo Mensual",
    finBonusMonths: "Meses Bono",
    finBonusTotal: "Bono al 100%",
    finFrequency: "Periodicidad",
    finMonthlyBudget: "Presupuesto Mensual",

    // Finance - Current Analysis
    finCurrentPageDesc: "Captura de datos reales y comparativo contra presupuesto",
    finRealDataCapture: "Captura Datos Reales",
    finRealVsBudget: "Real vs Presupuesto",
    finAnalysisGuide: "Guía de Análisis",
    finMonth: "Mes",
    finIncome: "Ingresos",
    finNetTotal: "Neto",
    finAccumReal: "Acumulado Real",
    finAccumBudget: "Acumulado Presupuesto",
    finVariance: "Varianza",
    finFavorable: "Favorable",
    finBudget: "Ppto.",
    finDiff: "Dif.",
    finGuideStep1Title: "Captura de datos históricos",
    finGuideStep1Desc: "Registra los datos de ventas, costos y gastos del año anterior como base de comparación.",
    finGuideStep2Title: "Genera proyecciones",
    finGuideStep2Desc: "Utiliza las herramientas de proyección para estimar ingresos y gastos del período actual.",
    finGuideStep3Title: "Captura datos reales",
    finGuideStep3Desc: "Mes a mes, registra los datos reales de operación para comparar contra el presupuesto.",
    finGuideStep4Title: "Analiza varianzas",
    finGuideStep4Desc: "Revisa las diferencias entre real y presupuesto, identifica causas y ajusta estrategias.",
  },
  en: {
    // General
    loading: "Loading...",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    actions: "Actions",
    search: "Search...",
    seeAll: "See all",
    noDescription: "No description",
    confirmDelete: "Are you sure you want to delete {count} risk(s)?",
    errorDeleting: "Error deleting risks.",
    deleting: "Deleting...",
    
    // Risk Levels
    intolerable: "Intolerable",
    high: "High",
    medium: "Medium",
    low: "Low",
    tolerable: "Tolerable",
    unclassified: "Unclassified",

    // Layout & Login
    riskManagement: "Risk Manager",
    professionalManagement: "Professional Management",
    dashboard: "Dashboard",
    departments: "Departments",
    allRisks: "Risk Matrix",
    addRisk: "Add Risk",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    logout: "Log Out",
    
    // New Login Translations
    loginWelcomeTitle: "Welcome Back",
    loginWelcomeSubtitle: "Access your risk management system",
    loginHeroSubtitle: "Professional system for comprehensive identification, evaluation, and management of organizational risks",
    loginButton: "Sign In",
    loginButtonLoading: "Signing In...",
    loginDisclaimer: "By logging in, you agree that your data will be kept private and secure",
    
    // Login Features
    loginFeature1Title: "Secure Access",
    loginFeature1Description: "Safe and fast authentication with your Google account",
    loginFeature2Title: "Private Data",
    loginFeature2Description: "Your information is protected with enterprise-grade encryption",
    loginFeature3Title: "Professional Matrix",
    loginFeature3Description: "Advanced tools for comprehensive risk management",
    loginNoAccount: "Don't have an account?",
    loginRegisterLink: "Register here",
    forgotPassword: "Forgot Password?",
    loginError: "Login error",
    invalidCredentials: "Invalid email or password",
    accountSuspended: "Your account has been suspended. Please contact the administrator.",


    // Forgot Password & Update Password
    recoverPasswordTitle: "Recover Password",
    recoverPasswordSubtitle: "Enter your email to receive a recovery link.",
    emailRequired: "Email is required",
    recoverPasswordSuccess: "Check your email for the recovery link",
    recoverPasswordError: "Error sending email. Please try again.",
    sending: "Sending...",
    emailSent: "Email Sent",
    sendRecoveryLink: "Send Recovery Link",
    backToLogin: "Back to Login",

    updatePasswordTitle: "New Password",
    updatePasswordSubtitle: "Enter your new password below.",
    passwordUpdatedSuccess: "Password updated successfully",
    updatePasswordError: "Error updating password. Please try again.",
    updating: "Updating...",
    updated: "Updated",
    updatePassword: "Update Password",


    // Register Page
    registerTitle: "Create New Account",
    registerSubtitle: "Register with your invitation code",
    registerHeroSubtitle: "Join our professional risk management platform",
    registerFullName: "Full Name",
    registerConfirmPassword: "Confirm Password",
    registerInvitationCode: "Invitation Code",
    registerButton: "Create Account",
    registerButtonLoading: "Creating Account...",
    registerSuccess: "Account created successfully! Redirecting...",
    registerAlreadyHaveAccount: "Already have an account?",
    registerLoginLink: "Sign in",
    registerCodeInfo: "You need a valid invitation code to register",

    // Register Form Validation
    registerAllFieldsRequired: "All fields are required",
    registerPasswordTooShort: "Password must be at least 6 characters",
    registerPasswordsDoNotMatch: "Passwords do not match",
    registerInvalidEmail: "Email is not valid",
    registerInvalidCode: "Invitation code is not valid",
    registerCodeUsed: "This code has already been used",
    registerCodeExpired: "The invitation code has expired",
    registerEmailExists: "This email is already registered",
    registerError: "Error creating account. Please try again.",

    // Register Features
    registerFeature1Title: "Exclusive Access",
    registerFeature1Description: "Invitation-only registration to maintain service quality",
    registerFeature2Title: "Secure Data",
    registerFeature2Description: "Your information protected with the highest security standards",
    registerFeature3Title: "Pro Tools",
    registerFeature3Description: "Full access to all professional features",

    // Dashboard
    welcome: "Welcome!",
    dashboardHeaderSubtitle: "Manage your organization's risks professionally.",
    newRisk: "New Risk",
    active: "Active",
    totalRisks: "Total Risks",
    identified: "Identified",
    highRisks: "High Risks",
    immediateAttention: "Immediate attention",
    lowRisks: "Low Risks",
    underControl: "Under control",
    recentDepartments: "Recent Departments",
    noDepartmentsRegistered: "No departments registered.",
    createFirstDepartment: "Create first department",
    riskDistribution: "Risk Distribution",
    noRisksRegistered: "No risks registered.",
    registerFirstRisk: "Register first risk",

    // Departments Page
    departmentsTitle: "Departments",
    departmentsSubtitle: "Manage departments and their associated risks.",
    newDepartment: "New Department",
    totalRisksLabel: "Total Risks",
    highRisksLabel: "High Risks",
    viewRisks: "View Risks",
    noDepartmentsFound: "No departments found",
    noDepartmentsFoundSubtitle: "Start by creating your first department to manage risks.",
    
    // AddDepartment Page
    addDepartmentTitle: "New Department",
    addDepartmentSubtitle: "Create a new department to manage risks.",
    editDepartmentTitle: "Edit Department",
    editDepartmentSubtitle: "Update the department's details.",
    departmentInfo: "Department Information",
    departmentNameLabel: "Department Name *",
    departmentNamePlaceholder: "E.g., Human Resources, IT, Finance...",
    descriptionLabel: "Description (Optional)",
    descriptionPlaceholder: "Describe the main functions of the department...",
    creating: "Creating...",
    createDepartment: "Create Department",
    errorRequiredName: "Department name is required.",
    errorCreatingDepartment: "Error creating department. Please try again.",
    errorUpdatingDepartment: "Error updating department. Please try again.",
    departmentNotFound: "Department not found.",

    // Risk Pages (General)
    riskInfo: "Basic Information",
    departmentLabel: "Department *",
    departmentPlaceholder: "Select department",
    threatTypeLabel: "Threat Type *",
    threatTypePlaceholder: "Select type",
    threatInternal: "Internal",
    threatExternal: "External",
    riskDescriptionLabel: "Risk Description *",
    riskDescriptionPlaceholder: "Describe the risk in detail...",
    inherentRiskEval: "Inherent Risk Assessment",
    inherentProbability: "Inherent Probability",
    inherentImpact: "Inherent Impact",
    selectProbability: "Select probability",
    selectImpact: "Select impact",
    inherentRiskLevel: "Inherent Risk Level:",
    strategyAndMitigation: "Strategy and Mitigation",
    managementStrategy: "Management Strategy",
    selectStrategy: "Select strategy",
    strategyAceptar: "Accept",
    strategyReducir: "Reduce",
    strategyTransferir: "Transfer",
    strategyEvitar: "Avoid",
    mitigationMeasure: "Mitigation Measure {num}",
    mitigationDescription: "Describe measure {num}...",
    mitigationImpact: "Expected impact...",
    selectMitigationImpact: "Select mitigation type...",
    "Mitiga la probabilidad": "Mitigates probability",
    "Mitiga el impacto": "Mitigates impact",
    "Mitiga la probabilidad e impacto": "Mitigates probability and impact",
    residualRisk: "Residual Risk",
    residualProbability: "Residual Probability",
    residualImpact: "Residual Impact",
    residualRiskLevel: "Residual Risk Level:",
    saving: "Saving...",
    saveChanges: "Save Changes",
    registerRisk: "Register Risk",
    errorRequiredFields: "Please complete all required fields (*)",
    errorSavingRisk: "Error saving risk. Please try again.",
    riskNotFound: "Risk not found.",
    dataLoadError: "Could not load necessary data.",

    // AddRisk Page
    addRiskTitle: "Register New Risk",
    addRiskSubtitle: "Document and evaluate an organizational risk.",
    editRiskTitle: "Edit Risk",
    editRiskSubtitle: "Update the details of the risk.",

    // DepartmentRisks Page
    departmentRiskManagement: "Risk management for the department",
    filtersAndSearch: "Filters and Search",
    searchRisksPlaceholder: "Search risks...",
    riskLevelLabel: "Risk level",
    allThreats: "All threats",
    riskList: "Risk List ({count})",
    tableDescription: "Description",
    tableType: "Type",
    tableInherentLevel: "Inherent Level",
    tableResidualLevel: "Residual Level",
    tableStrategy: "Strategy",
    noRisksFound: "No risks found",
    noRisksInDepartment: "No risks registered in this department.",
    noRisksMatchFilters: "No risks match the filters.",

    // AllRisks Page
    allRisksTitle: "Risk Matrix",
    allRisksSubtitle: "Centralized view of all organizational risks.",
    deleteSelected: "Delete ({count})",
    searchAllPlaceholder: "Search by area, description...",
    allDepartments: "All departments",
    showingRisks: "Showing {count} of {total} risks",
    tableDepartment: "Department",
    tableThreatType: "Threat Type",
    tableInherentProb: "Probability",
    tableInherentImp: "Impact",
    tableInherentLvl: "Level",
    tableHandling: "Handling",
    tableMitigant1: "Mitigant 1",
    tableMitigant2: "Mitigant 2",
    tableMitigant3: "Mitigant 3", 
    tableImpact: "Impact",
    tableImpact1: "Impact 1",
    tableImpact2: "Impact 2",
    tableImpact3: "Impact 3",
    tableResidualProb: "Probability",
    tableResidualImp: "Impact",
    tableResidualLvl: "Level",
    
    // Probabilities & Impacts (enums)
    "Remoto (0-20%)": "Remote (0-20%)",
    "Improbable (21-40%)": "Unlikely (21-40%)",
    "Ocasional (41-60%)": "Occasional (41-60%)",
    "Probable (61-80%)": "Likely (61-80%)",
    "Frecuente (81-100%)": "Frequent (81-100%)",
    "Insignificante": "Insignificant",
    "Menor": "Minor",
    "Crítico": "Critical",
    "Mayor": "Major",
    "Catastrófico": "Catastrophic",

    // Control Evaluation (Type & Grade)
    controlEvaluation: "Control Evaluation",
    controlType: "Control Type",
    controlPreventive: "Preventive Control",
    controlCorrective: "Corrective Control",
    controlDetective: "Detective Control",
    controlDocumented: "Documented control?",
    processType: "Process type",
    processManual: "Manual",
    processAutomated: "Automated",
    processCombined: "Combined",
    controlEvidence: "Generates auditable evidence?",
    controlResponsible: "Has a responsible person?",
    controlFrequency: "Executed frequently?",
    controlGrade: "Control Grade",
    gradeStrong: "Strong",
    gradeMedium: "Medium",
    gradeWeak: "Weak",
    yes: "Yes",
    no: "No",
    selectControlType: "Select control type...",
    selectProcessType: "Select process type...",
    selectYesNo: "Select...",
    tableControlType1: "Control Type 1",
    tableControlGrade1: "Control Grade 1",
    tableControlType2: "Control Type 2",
    tableControlGrade2: "Control Grade 2",
    tableControlType3: "Control Type 3",
    tableControlGrade3: "Control Grade 3",

    // Access Control
    accessDenied: "Access Denied",
    adminOnlyFeature: "This feature is only available for administrators.",
    contactAdminAccess: "If you need access, contact the system administrator.",

    // Invitation Codes Page
    invitationCodes: "Invitation Codes",
    codesTitle: "Invitation Codes",
    codesSubtitle: "Manage access codes for new users",
    codesCreateButton: "Generate Code",
    codesCreateTitle: "Generate New Code",
    codesCreateDescription: "Create an invitation code to allow a new user to register",
    codesEmailLabel: "User Email",
    codesEmailPlaceholder: "user@example.com",
    codesEmailHelp: "Optional: link this code to a specific email",
    codesNotesLabel: "Notes",
    codesNotesPlaceholder: "Client paid monthly plan, etc.",
    codesExpiryLabel: "Expiration Date",
    optional: "optional",
    create: "Create",
    codesStatTotal: "Total Codes",
    codesStatUsed: "Codes Used",
    codesStatAvailable: "Codes Available",
    codesListTitle: "All Codes",
    codesListDescription: "Manage and monitor invitation code usage",
    codesEmpty: "No invitation codes yet",
    codesTableCode: "Code",
    codesTableStatus: "Status",
    codesTableEmail: "Email",
    codesTableNotes: "Notes",
    codesTableCreated: "Created",
    codesTableExpires: "Expires",
    codesTableActions: "Actions",
    codesStatusUsed: "Used",
    codesStatusExpired: "Expired",
    codesStatusAvailable: "Available",
    codesDeleteTitle: "Delete Code?",
    codesDeleteDescription: "This action cannot be undone. The code will be permanently deleted.",
    codesLoadError: "Error loading codes",
    codeCreatedSuccess: "Code created successfully",
    codeCreateError: "Error creating code",
    codeDeletedSuccess: "Code deleted successfully",
    codeDeleteError: "Error deleting code",
    codeCopied: "Code copied to clipboard",
    codeCopyError: "Error copying code",

    // User Management Page
    userManagement: "User Management",
    usersTitle: "User Management",
    usersSubtitle: "Manage system user accounts",
    usersRefresh: "Refresh",
    usersStatTotal: "Total Users",
    usersStatActive: "Active Users",
    usersStatSuspended: "Suspended Users",
    usersSearchPlaceholder: "Search by name or email...",
    usersListTitle: "All Users",
    usersShowingCount: "Showing {count} of {total} users",
    usersEmpty: "No users registered",
    usersTableName: "Name",
    usersTableEmail: "Email",
    usersTableRole: "Role",
    usersTableStatus: "Status",
    usersTableCreated: "Registered",
    usersTableLastLogin: "Last Login",
    usersStatusActive: "Active",
    usersStatusSuspended: "Suspended",
    usersYou: "(You)",
    usersSuspendBtn: "Suspend",
    usersReactivateBtn: "Reactivate",
    usersSuspendTitle: "Suspend user?",
    usersSuspendDescription: "The user will not be able to sign in until reactivated. Their data will be preserved.",
    usersReactivateTitle: "Reactivate user?",
    usersReactivateDescription: "The user will be able to sign in again.",
    userSuspendedSuccess: "User suspended successfully",
    userSuspendError: "Error suspending user",
    userReactivatedSuccess: "User reactivated successfully",
    userReactivateError: "Error reactivating user",
    usersLoadError: "Error loading users",

    // Finance System - Dashboard
    finDashboardTitle: "Planning System",
    finDashboardSubtitle: "Comprehensive business and financial planning",
    finBizPlanningTitle: "Business Planning",
    finBizPlanningSubtitle: "Market, internal, customer and financial analysis",
    finFinPlanningTitle: "Financial Planning",
    finFinPlanningSubtitle: "Historical data, projections and current analysis",
    finBizAnalysis: "Business Analysis",
    finBizAnalysisDesc: "Market, internal analysis, customer and income statement",
    finSwot: "SWOT & Conclusions",
    finSwotDesc: "SWOT matrix, strategy summary and timeline",
    finHistorical: "Historical Analysis",
    finHistoricalDesc: "Historical sales data, income statement and cash flow",
    finProjection: "Financial Projection",
    finProjectionDesc: "Projection tools, consultation and quotation tools",
    finCurrent: "Current Analysis",
    finCurrentDesc: "Real data capture and budget comparison",
    finEnter: "Enter",
    finStatRevenue: "Annual Revenue",
    finStatMargin: "Gross Margin",
    finStatStrategies: "Strategies",
    finStatActive: "active",
    finStatPeriod: "Current Period",
    finStatInProgress: "In progress",
    finPlanning: "Planning",

    // Finance - Business Analysis
    finBizAnalysisPageDesc: "Comparative market, internal, customer and financial analysis",
    finTabMarket: "The Market",
    finTabInternal: "Internal Analysis",
    finTabCustomer: "The Customer",
    finTabFinStatus: "Income Statement",
    finSubTabCompetitors: "Your Competitors",
    finSubTabPosition: "Your Market Position",
    finSubTabExternal: "Your External Environment",
    finCompetitorAnalysis: "Competitor Comparative Analysis",
    finCompetitor: "Competitor",
    finPrice: "Price",
    finService: "Service",
    finPostSale: "Post-Sale",
    finDelivery: "Delivery",
    finMarketPosition: "Your Market Position",
    finStrengths: "Strengths",
    finWeaknessesToManage: "Weaknesses to Manage",
    finExternalEnv: "Your External Environment",
    finOpportunities: "Opportunities",
    finThreats: "Threats",
    finInternalAnalysis: "Internal Business Analysis",
    finCustomerAnalysis: "Customer Analysis",
    finCustProblem: "What problem(s) does your product/service solve?",
    finCustDesire: "What desire(s) does it address?",
    finCustFunctionalGoals: "Customer's functional goals",
    finCustEmotionalGoals: "Customer's emotional goals",
    finCustBasicNeeds: "Customer's basic needs",
    finFinancialStatus: "Financial Status Analysis",
    finCategory: "Category",
    finIsWeakness: "Is Weakness?",
    finDescription: "Description",
    finGoToConclusions: "Go to Conclusions",

    // Finance - SWOT / Conclusions
    finConclusionsTitle: "Conclusions",
    finConclusionsSubtitle: "SWOT, strategy summary and timeline",
    finSwotMatrix: "SWOT Matrix",
    finStrategySummary: "Strategy Summary",
    finTimeline: "Timeline",
    finWeaknesses: "Weaknesses",
    finThreatsLabel: "Threats",
    finAddItem: "Add item",
    finTask: "Task",
    finResponsible: "Responsible",
    finStart: "Start",
    finEnd: "End",
    finStatus: "Status",
    finStatusCompleted: "Completed",
    finStatusInProgress: "In Progress",
    finStatusPending: "Pending",

    // Finance - Financial History
    finHistoricalPageDesc: "Capture and query historical financial data",
    finSalesData: "Sales Data",
    finIncomeStatement: "Income Statement",
    finCashFlow: "Cash Flow",
    finHistSales: "Historical Sales",
    finReturns: "Returns",
    finNetTotals: "Net Sales",
    finPrint: "Print",
    finProductLine: "Product Line",
    finConcept: "Concept",
    finAll: "All",
    finOperationActivities: "Operating Activities",
    finOperationFlow: "Operating Cash Flow",
    finInvestActivities: "Investing Activities",

    // Finance - Projection
    finProjectionPageDesc: "Financial projection tools and quotation calculators",
    finProjMenu: "Projection Menu",
    finProjConsult: "Projection Inquiry",
    finQuotation: "Quotation Tools",
    finProjVsBase: "Monthly projections vs base year",
    finPosition: "Position",
    finMonthlySalary: "Monthly Salary",
    finBonusMonths: "Bonus Months",
    finBonusTotal: "100% Bonus",
    finFrequency: "Frequency",
    finMonthlyBudget: "Monthly Budget",

    // Finance - Current Analysis
    finCurrentPageDesc: "Real data capture and comparison against budget",
    finRealDataCapture: "Real Data Capture",
    finRealVsBudget: "Actual vs Budget",
    finAnalysisGuide: "Analysis Guide",
    finMonth: "Month",
    finIncome: "Income",
    finNetTotal: "Net",
    finAccumReal: "Accumulated Actual",
    finAccumBudget: "Accumulated Budget",
    finVariance: "Variance",
    finFavorable: "Favorable",
    finBudget: "Budget",
    finDiff: "Diff.",
    finGuideStep1Title: "Capture historical data",
    finGuideStep1Desc: "Record last year's sales, costs and expenses data as a comparison baseline.",
    finGuideStep2Title: "Generate projections",
    finGuideStep2Desc: "Use projection tools to estimate income and expenses for the current period.",
    finGuideStep3Title: "Capture real data",
    finGuideStep3Desc: "Month by month, record actual operating data to compare against budget.",
    finGuideStep4Title: "Analyze variances",
    finGuideStep4Desc: "Review differences between actual and budget, identify causes and adjust strategies.",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('es');

  useEffect(() => {
    const savedLang = localStorage.getItem('app-language') || 'es';
    setLanguage(savedLang);
  }, []);

  const changeLanguage = (lang) => {
    localStorage.setItem('app-language', lang);
    setLanguage(lang);
  };

  const t = (key, replacements = {}) => {
    let text = translations[language][key] || key;
    Object.keys(replacements).forEach(rKey => {
      text = text.replace(`{${rKey}}`, replacements[rKey]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
